#!/bin/bash

set -e

base_dir=$HOME

link() {
    src=$(pwd)/$1

    tgt_file=$2
    if [[ -z $tgt_file ]]; then
        tgt_file=".$1"
    fi

    tgt=$base_dir/$tgt_file
   
    mkdir -p $(dirname "$tgt")

    if [ -L "$tgt" ]; then
         echo "[WARNING] $tgt already symlinked"
         return
    fi

    if [ -e "$tgt" ]; then
        echo "[ERROR] $tgt exists but it's not a symlink. Please fix that manually"
        exit 1
    fi

    ln -s $src $tgt 
    echo "[OK] $src -> $tgt"
}

link bashrc
link zshrc
link profile
link gitconfig
link gitconfig.github

link vimrc
link vimrc .config/nvim/init.vim
