#!/bin/bash

set -e

link() {
    src=$(pwd)/$1

    if [ ! -e "$src" ]; then
        echo "[ERROR] File '$src' doesn't exist. Not creating symlink."
        exit 1
    fi

    tgt_file=${2:-.$1}
    tgt="$HOME/$tgt_file"

    mkdir -p $(dirname "$tgt")

    if [ -L "$tgt" ]; then
         echo "[WARNING] '$tgt' already symlinked"
         return
    fi

    if [ -e "$tgt" ]; then
        echo "[ERROR] '$tgt' exists but it's not a symlink. Please fix that manually"
        exit 1
    fi

    ln -s $src $tgt
    echo "[OK] $src -> $tgt"
}

link bashrc
link zshrc
link profile

link gitconfig
link gitconfig.github
link gitignore

link vimrc
link vimrc .config/nvim/init.vim

link pack .vim/pack
